# Generated by Django 5.2.11 on 2026-07-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letterpad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Medical Letter', max_length=255)),
                ('template_type', models.CharField(default='General', max_length=100)),
                ('content', models.TextField()),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('border_style', models.CharField(default='dental_frame', max_length=50)),
                ('hide_header', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letterpads', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterpads', to='app.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
