# Generated by Django 5.2.11 on 2026-06-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='new_patient',
            field=models.BooleanField(default=True),
        ),       
      
    ]
