# Generated by Django 5.2.11 on 2026-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationtemplate',
            name='food',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='food',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
