# Generated by Django 6.0.5 on 2026-06-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='new_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
