# Generated by Django 5.2.11 on 2026-06-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient_new_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_name1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
